---
author: "University of Melbourne Centre for Cancer Research"
date: "`r Sys.time()`"
output:
  html_document:
    theme: cosmo # darkly
    css: style.css
    toc: false
    code_download: true
  rmdformats::material:
    highlight: kate
params:
  af_global: NULL
  af_keygenes: NULL
  batch_name: NULL
  conda_list: NULL
  img_dir: NULL
  key_genes: NULL
  virusbreakend_tsv: NULL
  virusbreakend_vcf: NULL
  purple_purity: NULL
  purple_qc: NULL
  purple_som_cnv_ann: NULL
  purple_som_cnv: NULL
  purple_som_gene_cnv: NULL
  purple_som_snv_vcf: NULL
  result_outdir: NULL
  somatic_snv_vcf: NULL
  somatic_snv_summary: NULL
  somatic_sv_tsv: NULL
  somatic_sv_vcf: NULL
  title: "UMCCR Cancer Report"
  tumor_name: NULL
description: "Analysis of tumor/normal samples at UMCCR"
title: "`r paste(params$batch_name, params$title)`"
---

```{r knitr_opts, include=F}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE,
  warning = FALSE, message = FALSE,
  error = TRUE
) # continue running report even after chunk errors
```

```{r load_pkgs}
# CRAN
library(devtools)
library(details)
library(DT)
library(dplyr)
library(glue)
library(gt)
library(ggplot2)
library(htmltools)
library(jsonlite)
library(knitr)
library(kableExtra)
library(patchwork)
library(purrr)
library(readr)
library(rmarkdown)
library(stringr)
library(tidyr)
# umccr
library(gpgr)
library(sigrap)
```

```{r funcs}
bnm <- params$batch_name
img_dir <- params$img_dir # should be relative to the knitting directory
result_outdir <- params$result_outdir # directory to write tables to
blank_lines <- function(n = 10) {
  cat(rep("&nbsp;  ", n), sep = "\n")
}

# get js indices when using in DT options
col_ind_js <- function(dt, col) {
  ntab <- setNames((1:ncol(dt) - 1), names(dt))
  stopifnot(all(col %in% names(dt)))
  sort(unname(ntab[col]))
}

# used in SV table Details
sv_detail_table <- function(tab) {
  # for checking if the columns in the dt are all described
  check_cols_described <- function(cols, descr) {
    stopifnot(is.character(cols), is.atomic(cols))
    stopifnot(is.character(descr), is.atomic(descr))
    for (col in cols) {
      if (!col %in% descr) {
        warning(glue::glue("{col} is not described!"))
      }
    }
  }

  check_cols_described(colnames(tab), sv_col_descr$Column)
  list(Column = colnames(tab)) %>%
    tibble::as_tibble() %>%
    dplyr::left_join(sv_col_descr, by = "Column") %>%
    knitr::kable()
}
```

```{r sv_prep}
#---- Structural Variants ----#
sv_path <- params$somatic_sv_tsv
sv <- NULL
no_sv_found <- gpgr::tsv_is_empty(sv_path)
if (!no_sv_found) {
  sv <- gpgr::process_sv(sv_path)
}
```

## __Structural Variants__

```{r}
oncokb_database_fp <- "/Users/stephen/projects/sash_projects/cancer_report_sv_presentation__dev_rerun/5_seqc_example/other/cancerGeneList.tsv"
oncokb_genes <- gpgr::read_oncokb_database(oncokb_database_fp)

sv$annotations <- sv$annotations |>
  dplyr::mutate(
    "Involves OncoKB gene" = stringr::str_split(Genes, "[&-]") |> purrr::map_lgl(function(x) x %in% oncokb_genes |> any()),
    Genes = dplyr::pull(sv$annotations, Genes) |> purrr::map(gpgr::set_gene_oncokb_links, .progress=TRUE),
    .after = "Detail",
  )
```

```{r}
sv.dt <- sv |>
  purrr::map(function(x) {
    x |> DT::datatable(
      filter = list(position = "top", clear = FALSE, plain = TRUE),
      class = "cell-border display compact",
      rownames = FALSE, extensions = c("Scroller", "Buttons", "KeyTable"),
      options = list(
        scroller = TRUE, scrollY = 400, scrollX = TRUE, autoWidth = FALSE, keys = TRUE,
        buttons = c("csv", "excel"), dom = "Blfrtip"
      ),
      # Only disable HTML escaping in the Genes column
      escape = -which("Genes" %in% colnames(x))
    )
  })
```

### __Breakpoints and Breakends__ {.tabset .tabset-fade}

#### Prioritised

```{r}
sv.dt$annotations
```

```{r, results='asis'}
blank_lines(2)
```

#### Filtered

```{r}
sv.dt$annotations_filtered
```

```{r, results='asis'}
blank_lines(2)
```

#### Many transcripts

```{r}
sv.dt$many_transcripts
```

```{r, results='asis'}
blank_lines(2)
```
